github:
  description: "Fauxton is the new Web UI for CouchDB"
  homepage: https://github.com/apache/couchdb-fauxton
  labels:
    - apache
    - couchdb
    - fauxton
    - erlang
    - network-client
    - http
    - big-data
    - cloud
    - database
    - javascript
  protected_branches:
    main:
      required_status_checks:
        strict: true
        # contexts are the names of checks that must pass.
        "contexts":
          - run-unit-tests
          - run-e2e-tests
