github:
  description: "Fauxton is the new Web UI for CouchDB"
  homepage: https://github.com/apache/couchdb-fauxton
  labels:
    - apache
    - couchdb
    - fauxton
    - erlang
    - network-client
    - http
    - big-data
    - cloud
    - database
    - javascript
  protected_branches:
    main:
      required_status_checks:
        strict: true
        # contexts are the names of checks that must pass.
        contexts:
          - CI
      required_pull_request_reviews:
        # Set to true if you want to automatically dismiss approving reviews when someone pushes a new commit.
        dismiss_stale_reviews: false
        # Specifies the number of reviewers required to approve pull requests.
        # Use a number between 1 and 6 or 0 to not require reviewers.
        required_approving_review_count: 1
