version: '2'
services:
  couchdb:
    container_name: couchdb
    image: ${COUCHDB_IMAGE}
    environment:
      COUCHDB_USER: tester
      COUCHDB_PASSWORD: testerpass
    ports:
      - "5984:5984"
