/**
 * Created by sam on 14/07/2016.
 */
export default {
  EDIT_CONFIG: 'EDIT_CONFIG',
  LOADING_CONFIG: 'LOADING_CONFIG',
  EDIT_OPTION: 'EDIT_OPTION',
  CANCEL_EDIT: 'CANCEL_EDIT',
  SAVING_OPTION: 'SAVING_OPTION',
  OPTION_SAVE_SUCCESS: 'OPTION_SAVE_SUCCESS',
  OPTION_SAVE_FAILURE: 'OPTION_SAVE_FAILURE',
  DELETING_OPTION: 'DELETING_OPTION',
  OPTION_DELETE_SUCCESS: 'OPTION_DELETE_SUCCESS',
  OPTION_DELETE_FAILURE: 'OPTION_DELETE_FAILURE',
  ADDING_OPTION: 'ADDING_OPTION',
  OPTION_ADD_SUCCESS: 'OPTION_ADD_SUCCESS',
  OPTION_ADD_FAILURE: 'OPTION_ADD_FAILURE'
};
